### ISSUE TITLE
Error when server sends named sound packet [761 - 1.19.3]

### ISSUE THREAD

**Issue by TauCubed** [Exceptionflug/protocolize#170]
**Describe the bug**
Error when playing sounds via /playsound

**To Reproduce**
1. Join a 1.19.3 server with 1.19.3
2. run `/playsound minecraft:ambient.basalt_deltas.additions master @p ~ ~ ~`
3. Observe error

**Expected behavior**
The sound to play and no error.

**Screenshots**
```
[22:44:12 ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[22:44:12 ERROR]: [Protocolize] Protocolize 2.2.3:518
[22:44:12 ERROR]: [Protocolize] Stream Direction: DOWNSTREAM
[22:44:12 ERROR]: [Protocolize] Connection: TauCubed
[22:44:12 ERROR]: [Protocolize] Protocol version: 761
[22:44:12 ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 761 in direction TO_CLIENT
[22:44:12 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[22:44:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[22:44:12 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[22:44:12 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[22:44:12 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:44:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[22:44:12 ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 761 in direction TO_CLIENT
[22:44:12 ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 10
[22:44:12 ERROR]:       at dev.simplix.protocolize.data.packets.NamedSoundEffect.read(NamedSoundEffect.java:95)
[22:44:12 ERROR]:       at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:48)
[22:44:12 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[22:44:12 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[22:44:12 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[22:44:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[22:44:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[22:44:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[22:44:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[22:44:12 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[22:44:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[22:44:12 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[22:44:12 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:44:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Proxy environment**
`git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510`

**Minecraft versions used**
both 1.19.3 (waterfall & paper)

**Comment by TauCubed** [comment]
Also the Sounds.class enum is out of sync with the real values.

For instance, playing the sound `MUSIC_DRAGON` causes `MUSIC_CREDITS` to play.

**Comment by Exceptionflug** [comment]
Hey,

thank you for your report. I will take a look into this.

**Comment by Exceptionflug** [comment]
Should be fixed in 2.2.4

**Comment by TauCubed** [comment]
The sound enum issue still exists.

I'll create a new issue for it.
