### ISSUE TITLE
Error when opening inventory to 1.20.4 client

### ISSUE THREAD

**Issue by LaserSlime** [Exceptionflug/protocolize#211]
**Describe the bug**
[00:45:31 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765

I've tried to bump the data.version in pom.xml to 2.3.2 which was forgotten it seems like but that only lead to more weird errors about not being able to find grass blocks.

**To Reproduce**
1. Make a plugin open a protocolize inventory
2. See error

**Expected behavior**
The inventory should open

**Proxy environment**
git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556

**Minecraft versions used**
If applicable, tell us the used minecraft client AND server versions that are involved in this problem.

**Comment by Exceptionflug** [comment]
I will take a look at it when I have time

**Comment by homerek111** [comment]
> I will take a look at it when I have time

any news with that issue?

**Comment by homerek111** [comment]
> > I will take a look at it when I have time
> 
> any news with that issue?

anything...?

**Comment by Tig3r98** [comment]
@Exceptionflug looks like data.version wasn't updated to 2.3.2 in the pom of the protocolize module?

**Comment by Exceptionflug** [comment]
I'm currently ill... sorry for not responding

**Comment by LaserSlime** [comment]
> @Exceptionflug looks like data.version wasn't updated to 2.3.2 in the pom of the protocolize module?

I tried updating that and there's still issues.

**Comment by Exceptionflug** [comment]
Hey, sorry for the delay. It should be fixed now. Just download protocolize again from https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/artifact/protocolize-bungeecord/target/protocolize-bungeecord.jar

**Comment by LaserSlime** [comment]
Ok the player no longer gets kicked but the gui still doesnt open.
And there's this in console:
```
[15:19:24 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@37067345, receiver=LaserSlime), cancelled=false, tag=slimenetwork:main) to listener net.slimenetworkmc.bungee.listeners.PluginMessageListener@1e8b0ab5
java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.wrapper(dev.simplix.protocolize.api.packet.AbstractPacket)" because "pack" is null
        at dev.simplix.protocolize.bungee.player.BungeeCordProtocolizePlayer.sendPacket(BungeeCordProtocolizePlayer.java:52) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.openInventory(ProtocolizePlayer.java:110) ~[?:?]
        at net.slimenetworkmc.bungee.player.SlimeNetworkPlayer.openStatsGui(SlimeNetworkPlayer.java:120) ~[?:?]
        at net.slimenetworkmc.bungee.listeners.PluginMessageListener.on(PluginMessageListener.java:25) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:321) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at java.lang.Thread.run(Thread.java:842) [?:?]
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:24 WARN] [dev.simplix.protocolize.data.inventory.InventoryType]: [Protocolize] Unable to find typical inventory size of GENERIC_9X4 in version 765
[15:19:25 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@37067345, receiver=LaserSlime), cancelled=false, tag=slimenetwork:main) to listener net.slimenetworkmc.bungee.listeners.PluginMessageListener@1e8b0ab5
java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.wrapper(dev.simplix.protocolize.api.packet.AbstractPacket)" because "pack" is null
        at dev.simplix.protocolize.bungee.player.BungeeCordProtocolizePlayer.sendPacket(BungeeCordProtocolizePlayer.java:52) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.lambda$closeInventory$0(ProtocolizePlayer.java:71) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.closeInventory(ProtocolizePlayer.java:70) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.openInventory(ProtocolizePlayer.java:89) ~[?:?]
        at net.slimenetworkmc.bungee.player.SlimeNetworkPlayer.openStatsGui(SlimeNetworkPlayer.java:120) ~[?:?]
        at net.slimenetworkmc.bungee.listeners.PluginMessageListener.on(PluginMessageListener.java:25) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:321) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
        at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Comment by xxcodianxx** [comment]
Similar issue on Velocity `3.3.0-SNAPSHOT (git-00ef92bc-b312)` when trying to use inventory API:

```
java.lang.IllegalStateException: Cannot send dev.simplix.protocolize.data.packets.OpenWindow to players with protocol version 765
        at dev.simplix.protocolize.velocity.player.VelocityProtocolizePlayer.sendPacket(VelocityProtocolizePlayer.java:54) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.openInventory(ProtocolizePlayer.java:110) ~[?:?]
        ...
```

**Comment by homerek111** [comment]
> Hey, sorry for the delay. It should be fixed now. Just download protocolize again from https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/artifact/protocolize-bungeecord/target/protocolize-bungeecord.jar

Still can't open the gui:

[01:32:11 INFO] [ProtoGUI]: Opening gui servermenu for player a915280b-45da-31cc-a12f-01ca06da634e (target: tester420r)
[01:32:11 WARN]: Error in dispatching command
java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.wrapper(dev.simplix.protocolize.api.packet.AbstractPacket)" because "pack" is null
        at dev.simplix.protocolize.bungee.player.BungeeCordProtocolizePlayer.sendPacket(BungeeCordProtocolizePlayer.java:52) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.lambda$closeInventory$0(ProtocolizePlayer.java:71) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.closeInventory(ProtocolizePlayer.java:70) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.openInventory(ProtocolizePlayer.java:89) ~[?:?]
        at com.danifoldi.protogui.main.GuiHandler.open(GuiHandler.java:419) ~[?:?]
        at com.danifoldi.protogui.main.ProtoGuiAPI.openGui(ProtoGuiAPI.java:66) ~[?:?]
        at com.danifoldi.protogui.main.CommandHandler.dispatch(CommandHandler.java:81) ~[?:?]
        at com.danifoldi.protogui.platform.bungee.CommandWrapper.execute(CommandWrapper.java:49) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:215) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:166) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:248) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:200) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at net.md_5.bungee.protocol.packet.ClientCommand.handle(ClientCommand.java:109) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:140) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[flamecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by LaserSlime** [comment]
@Exceptionflug Have you ever considered maybe giving this plugin to someone else who is willing to maintain it? Because you don't seem to be interested in it anymore.

**Comment by Exceptionflug** [comment]
Of course I did. But there simply not really much interest from people in maintaining such a plugin.

**Comment by homerek111** [comment]
> Of course I did. But there simply not really much interest from people in maintaining such a plugin.

I believe you can find a solution for this inventory issue :)))

**Comment by Exceptionflug** [comment]
Is fixed for BungeeCord at least. There is currently no support for nbt serialization or deserialization in adventure.
https://github.com/KyoriPowered/adventure/issues/995

**Comment by homerek111** [comment]
> Is fixed for BungeeCord at least. There is currently no support for nbt serialization or deserialization in adventure. [KyoriPowered/adventure#995](https://github.com/KyoriPowered/adventure/issues/995)

not really fixed... it is actually more broken than before in my case

connection lost on 1.20.1:
[22:02:12 INFO] [ProtoGUI]: Opening gui servermenu for player 642cc634-262a-363e-9766-c0c12b0d78e1 (target: _homerek)
[22:02:12 INFO]: [_homerek] disconnected with: NoSuchMethodError : 'dev.simplix.protocolize.api.inventory.Inventory dev.simplix.protocolize.api.inventory.Inventory.title(java.lang.String)' @ com.danifoldi.protogui.main.GuiHandler:351
![obraz](https://github.com/Exceptionflug/protocolize/assets/93496464/79a87602-958e-44ef-9599-6ad60ff92551)

connection lost on 1.20.4:
[22:14:59 INFO] [ProtoGUI]: Opening gui servermenu for player a915280b-45da-31cc-a12f-01ca06da634e (target: tester420r)
[22:14:59 INFO]: [tester420r] disconnected with: NoSuchMethodError : 'dev.simplix.protocolize.api.inventory.Inventory dev.simplix.protocolize.api.inventory.Inventory.title(java.lang.String)' @ com.danifoldi.protogui.main.GuiHandler:351
![obraz](https://github.com/Exceptionflug/protocolize/assets/93496464/645fffe3-ccc7-42da-851f-7b5a34230539)

warn spam on bungeecord server's start
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 393
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 401
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 404
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 477
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 480
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 485
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 490
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 498
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 573
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 575
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 578
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 735
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 736
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 751
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 753
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 754
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 755
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 756
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 757
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 758
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 759
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 760
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 761
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 762
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 763
[21:58:32 WARN] [Protocolize]: Don't know what item GRASS was at protocol 764
[21:58:33 INFO] [Protocolize]: Enabled module dev.simplix.protocolize.data.DataModule
[21:58:33 INFO]: Enabled plugin Protocolize version 2.3.3:927 by Exceptionflug

[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.
[21:58:33 WARN] [ProtocolizeLegacySupport]: Don't know what old item type GRASS is.

**Comment by Exceptionflug** [comment]
This is no longer an issue of protocolize. The latest update included some API changes which will cause plugins to break. ProtoGUI needs to get updated before it is usable again.

**Comment by homerek111** [comment]
> This is no longer an issue of protocolize. The latest update included some API changes which will cause plugins to break. ProtoGUI needs to get updated before it is usable again.

in that case im stack with this... As i see ProtoGUI's author does not really support the plugin...

**Comment by LaserSlime** [comment]
```
[22:26:49] [Netty Worker IO Thread #7/ERROR] [Protocolize]: Unable to read item stack from buffer in protocol version 764
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.io.StringReader.<init>(StringReader.java:51) ~[?:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at dev.simplix.protocolize.bungee.providers.BungeeCordComponentConverterProvider$BungeeCordComponentConverter.fromJson(BungeeCordComponentConverterProvider.java:73) ~[?:?]
	at dev.simplix.protocolize.bungee.providers.BungeeCordComponentConverterProvider$BungeeCordComponentConverter.fromJson(BungeeCordComponentConverterProvider.java:32) ~[?:?]
	at dev.simplix.protocolize.api.chat.ChatElementImpl.ofJson(ChatElementImpl.java:25) ~[?:?]
	at dev.simplix.protocolize.api.chat.ChatElement.ofJson(ChatElement.java:20) ~[?:?]
	at dev.simplix.protocolize.api.item.ItemStackSerializer.read(ItemStackSerializer.java:66) ~[?:?]
	at dev.simplix.protocolize.data.packets.ClickWindow.read(ClickWindow.java:88) ~[?:?]
	at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:55) ~[?:?]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:517) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```
I'm getting weird errors in console when players move items in chests. It also causes ghost items sometimes.

**Comment by homerek111** [comment]
> > This is no longer an issue of protocolize. The latest update included some API changes which will cause plugins to break. ProtoGUI needs to get updated before it is usable again.
> 
> in that case im stack with this... As i see ProtoGUI's author does not really support the plugin...
> 
> Is there any possibility to get help from you... Im not dev and can't really adapt protogui code to new api on my own :/

protogui dev said he can help :)

**Comment by Exceptionflug** [comment]
> The plugin does work on 1.20.4 after updating [BungeeGUI](https://github.com/Tig3r98/BungeeGUI) to 1.1.0. But I can reproduce part of @homerek111's problem: the startup error
> 
> ```
> Don't know what item GRASS was at protocol 393
> Don't know what item GRASS was at protocol 401
> Don't know what item GRASS was at protocol 404
> Don't know what item GRASS was at protocol 477
> Don't know what item GRASS was at protocol 480
> Don't know what item GRASS was at protocol 485
> Don't know what item GRASS was at protocol 490
> Don't know what item GRASS was at protocol 498
> Don't know what item GRASS was at protocol 573
> Don't know what item GRASS was at protocol 575
> Don't know what item GRASS was at protocol 578
> Don't know what item GRASS was at protocol 735
> Don't know what item GRASS was at protocol 736
> Don't know what item GRASS was at protocol 751
> Don't know what item GRASS was at protocol 753
> Don't know what item GRASS was at protocol 754
> Don't know what item GRASS was at protocol 755
> Don't know what item GRASS was at protocol 756
> Don't know what item GRASS was at protocol 757
> Don't know what item GRASS was at protocol 758
> Don't know what item GRASS was at protocol 759
> Don't know what item GRASS was at protocol 760
> Don't know what item GRASS was at protocol 761
> Don't know what item GRASS was at protocol 762
> Don't know what item GRASS was at protocol 763
> Don't know what item GRASS was at protocol 764
> Enabled module dev.simplix.protocolize.data.DataModule
> Enabled plugin Protocolize version 2.3.3:926 by Exceptionflug
> ```
> 
> It should be noted that GRASS was renamed SHORT_GRASS in 1.20.3 @Exceptionflug I didn't try to put a grass in a gui.

Thank you for pointing out. But this is a different topic. Please feel free to open a new issue for that. Since the original case is fixed now, I will close this.
