### ISSUE TITLE
Protocolize Doesn't know what item 575:0 is at version 578

### ISSUE THREAD

**Issue by plebexer** [Exceptionflug/protocolize#59]
hi!, i recently started using viaversion on my server and now im getting this error all the time in my proxy, is protocolize not compatible with viaversion?

error:
[Protocolize] Don't know what item 575:0 is at version 578

**Comment by Exceptionflug** [comment]
Hey, thank you for reporting this. At first: This is not an error. This is a warning that something is messed up with the protocol id mappings for the used protocol version. This helps me to further improve the minecraft item support. For endusers, this can be ignored or, in your case, reported. Reporting such warnings helps me to improve the stability and compatibility of protocolize. I will keep you up to date when something has changed on that topic.

**Comment by Exceptionflug** [comment]
Is now fixed. Please download latest version from ci: https://ci.exceptionflug.de/job/Protocolize/

**Comment by plebexer** [comment]
i dont know what could be causing it but i still get this problem on the lastest build

`>.... [13:52:03] [WARN]: [Protocolize] Don't know what item 575:0 is at version 578`

**Comment by plebexer** [comment]
the plugin works fine because it is a warning, but is there a way to make it so it wont spam the proxy console?

**Comment by Exceptionflug** [comment]
> 
> 
> i dont know what could be causing it but i still get this problem on the lastest build
> 
> `>.... [13:52:03] [WARN]: [Protocolize] Don't know what item 575:0 is at version 578`

Oh yeah figured out why.



> 
> 
> the plugin works fine because it is a warning, but is there a way to make it so it wont spam the proxy console?

No sadly not.

**Comment by plebexer** [comment]
hi!, sorry for the late response but i have been bussy, im still getting this error on the lastest spigot version you released

[Protocolize] Don't know what item 575:0 is at version 578

**Comment by Exceptionflug** [comment]
Yeah this fix is not included in the current spigot release. Please download the latest build from here: https://ci.exceptionflug.de/job/Protocolize/
